---
name: Prepare Release

on:
  push:
    branches:
      - master

jobs:
  versioning:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Versioning and Changelog

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Versioning and Changelog
        run: |
          npx standard-version

      - name: Push to Repository
        run: |
          git config --local user.email "${{ env.GITHUB_ACTION }}+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git push --follow-tags
